apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkyc-apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: pkyc
        image: us.icr.io/pkyc_evaluation/pkyc-evaluation:1.1
        ports:
        - containerPort: 8080
        env:
         - name: PROJECT_ID
           value: "cf7bf905-cfb9-4759-92fd-3c8b1cd37930"
         - name: IBM_CLOUD_API_KEY
           valueFrom:
             secretKeyRef:
               name: pkyc-api-secret
               key: ibm_cloud_api_key
         - name: API_KEY
           valueFrom:
             secretKeyRef:
               name: pkyc-api-secret
               key: api_key
---
apiVersion: v1
kind: Service
metadata:
  name: pkyc-service
spec:
  selector:
    app: fastapi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32001
  type: NodePort